---

build: off

before_test:
  - choco install ghc
  - choco install cabal

test_script:
  - refreshenv
  - cabal new-update
  - cabal new-build all
  - ps: $directory = Get-ChildItem . -name -recurse archive-backpack.exe
  - ps: Copy-Item $directory archive-backpack-x86_64-pc-windows.exe
  - ps: Push-AppveyorArtifact archive-backpack-x86_64-pc-windows.exe

deploy:
  artifacts: archive-backpack-x86_64-pc-windows.exe
  provider: GitHub
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: # put yours here

branches:
  only:
    - master
    - /\d+\.\d+\.\d+\.\d+.*$/
