#!/usr/bin/env bash

set -e

sn d sparc64-linux-dist.tar*

for tarball in sparc64-linux-dist.tar.zst sparc64-linux-dist.tar.lz
do
    bench "bsdtar -xf $tarball" "hstar unpack $tarball" "tar xf $tarball" "star xf $tarball" --before 'rm -rf language-dickinson-1.1.0.2'
done

bench 'lzip -cd sparc64-linux-dist.tar.lz | busybox tar xf -' \
    'zstd -cd sparc64-linux-dist.tar.zst | busybox tar xf -'

for tarball in sparc64-linux-dist.tar.gz sparc64-linux-dist.tar.xz sparc64-linux-dist.tar.bz2
do
    bench "python3 -m tarfile -e $tarball" "bsdtar -xf $tarball" "hstar unpack $tarball" "tar xf $tarball" "star xf $tarball" "arc -overwrite unarchive $tarball" --before 'rm -rf language-dickinson-1.1.0.2'
done

bench 'busybox tar xzf sparc64-linux-dist.tar.gz' \
    'busybox tar xjf sparc64-linux-dist.tar.bz2' \
    'busybox tar xJf sparc64-linux-dist.tar.xz'

# 'arc unarchive sparc64-linux-dist.tar.lz4' \
bench 'bsdtar -xf sparc64-linux-dist.tar.lz4' \
    'hstar unpack sparc64-linux-dist.tar.lz4' \
    'lz4 -cd sparc64-linux-dist.tar.lz4 | busybox tar xf -' \
    'lz4 -cd sparc64-linux-dist.tar.lz4 | tar xf -' \
    'lz4 -cd sparc64-linux-dist.tar.lz4 | star xf -' --before 'rm -rf language-dickinson-1.1.0.2'
