#!/usr/bin/env bash

set -e

for tarball in ghc-8.8.2-x86_64-deb9-linux.tar.gz ghc-8.8.2-x86_64-deb9-linux.tar.lz ghc-8.8.2-x86_64-deb9-linux.tar.xz ghc-8.8.2-x86_64-deb9-linux.tar.bz2 ghc-8.8.2-x86_64-deb9-linux.tar.zst
do
    bench "bsdtar -xf $tarball" "hstar unpack $tarball ." "tar xf $tarball"
done
